[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20

decorations = "Full"
opacity = 0.8
blur = true

[font]
normal.family = "FiraMono Nerd Font Mono"
size = 20

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
